### ISSUE TITLE
If using default hostadresse it fails as you manually add port 8080 to it

### ISSUE THREAD

**Issue by Crowdedlight** [GRVYDEV/Lightspeed-webrtc#10]
If you give no argument so it uses the default, then it will use:
```go
addr         = flag.String("addr", "localhost:8080", "http service address")
``` 
Which causes this error:
```
➜ docker run --rm -it --name webrtc-test webrtc-test
Waiting for RTP Packets
listen tcp: address localhost:8080:8080: too many colons in address
``` 
I assume the error is caused when it tries to use it in L86:
```
log.Fatal(http.ListenAndServe(*addr+":8080", nil))
```
(https://github.com/GRVYDEV/Lightspeed-webrtc/blob/main/main.go#L86)
And you manually add 8080 to it. 

Probably enough just to remove :8080 from the default argument in L25

**Comment by GRVYDEV** [comment]
Weird someone else must have added that in there! ;) All jokes aside yeah we can remove the :8080 from the default value and that will solve that problem. I did this because before it required 2 flags of the same address just one with a port and without a port and I missed changing the default value. Good catch!

**Comment by Crowdedlight** [comment]
> Weird someone else must have added that in there! ;) All jokes aside yeah we can remove the :8080 from the default value and that will solve that problem. I did this because before it required 2 flags of the same address just one with a port and without a port and I missed changing the default value. Good catch!

haha fair enough :)

**Comment by GRVYDEV** [comment]
Fixed :)
